spring.application.name=streak_tracker

spring.data.mongodb.uri=mongodb://localhost:27017/streakapp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=streakmailfunctionality@gmail.com
spring.mail.password=example-password
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8